import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AddressProvider } from "@/components/Context/Address";
import { RoadProvider } from "@/components/Context/Road";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taxi app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RoadProvider>
          <AddressProvider>{children}</AddressProvider>
        </RoadProvider>
      </body>
    </html>
  );
}
